hw1: hw1 has been done.
Macbeth-Klm/Tinkoff-java-course-2024 pull request #1
Opened 2024-02-12 14:24 UTC by Macbeth-Klm

Здравствуйте! Spring Framework только начал изучать, поэтому надеюсь на столь же полезные рекомендации, как и в прошлом семестре.

2024-02-12 23:54 UTC, Macbeth-Klm commented
Я не знаю, с чем может быть связана данная проблема, но мои тесты не учитываются, в результате чего PR выдаёт отсутствие покрытия кода тестами для всех команд. Подскажите, с чем может быть связана данная проблема.
Спасибо.

2024-02-16 09:46 UTC, nexen505 requested changes

2024-02-16 09:46 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/database/DatabaseImitation.java
> +    private static final Map<Long, List<URI>> STORAGE = new HashMap<>();
Проблема: коллекция непотокобезопасная, хоть использование хранилища подразумевает многопоточную среду из-за работы через веб-сервис.

Предложение: уточнить тип мапы до потокобезопасного.

2024-02-16 09:46 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/database/DatabaseImitation.java
> +public final class DatabaseImitation {
Мысль: можешь подумать над тем, чтобы сделать этот класс бином тоже.

2024-02-16 09:46 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/database/DatabaseImitation.java
> +    public static void addSubscriptionToUser(Long chatId, URI link) {
Проблема: тут и в других методах не обрабатывается случай, если чат еще не был зарегистрирован, что приведет к `NullPointerException`.

Предложение: обработать такую ситуацию.

2024-02-16 09:46 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/Bot.java
> +    @Autowired
Косметика: в Spring Boot можно не писать аннотацию в данном случае: единственный конструктор компонента автоматически распознается как основной.

2024-02-16 09:46 UTC, nexen505 commented on bot/src/test/java/edu/java/bot/CommandsTest.java
> +public class CommandsTest {
Предложение: расширить тесты тестами и других введенных классов.

2024-02-19 12:39 UTC, nexen505 requested changes

2024-02-19 12:39 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/database/DatabaseImitation.java
> +        storage.put(chatId, new ArrayList<>());
Проблема: `ArrayList` непотокобезопасен, а используется в многопоточной среде.

Предложение: использовать либо синхронизированный список, либо потокобезопасный.

2024-02-19 12:39 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/database/DatabaseImitation.java
> +            var subscriptions = storage.get(chatId);
Мысль: тут и в соседних методах `get` + `isRegisteredUser` читаю из мапы ключ два раза, что излишне, исходя из необходимости обеспечения потокобезопасности.

2024-02-26 11:23 UTC, nexen505 approved these changes

2024-02-26 12:13 UTC, merged