hw6: hw6 has been done
Macbeth-Klm/Tinkoff-java-course-2024 pull request #10
Opened 2024-03-29 00:01 UTC by Macbeth-Klm

2024-04-08 12:08 UTC, nexen505 requested changes

2024-04-08 12:08 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scheduler/service/LinkUpdaterService.java
> +public interface LinkUpdaterService {
Проблема: насколько вижу, реализация классов во многом копипастится.

Предложение: зарефакторить, чтобы общая логика была в абстрактном классе и была завязана на интерфейсы, а компоненты реализовывали недостающие части за счет разных реализаций репозиториев.

2024-04-08 12:08 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scheduler/updater/jdbc/JdbcLinkUpdater.java
> +public interface JdbcLinkUpdater {
Проблема: насколько вижу, интерфейс копипастится с `JooqLinkUpdater` + `JpaLinkUpdater`, реализация классов во многом копипастится и недостает тестов.

Предложение: зарефакторить, чтобы общая логика была в абстрактном классе и была завязана на интерфейсы, а компоненты реализовывали недостающие части за счет разных реализаций репозиториев.

2024-04-08 23:58 UTC, Macbeth-Klm commented on scrapper/src/main/java/edu/java/scheduler/service/LinkUpdaterService.java
> +public interface LinkUpdaterService {
Я немного не понимаю, как это реализовать. Проблема заключается в том, что JPA-реализация работает с объектами `Link`, которые `@Entity`, а JDBC и JOOQ - с `LinkDto`. Из-за этого возникает трудность в решении проблемы копипаста, так как я не знаю, как сделать общую логику в абстрактном классе. У меня до этого были интерфейсы для каждого репозитория, но я ушел от этого в этом задании. Можно, конечно, написать обертку над JPA-реализациями, но мне кажется, что это уже излишне и костыльно что ли.

2024-04-09 00:03 UTC, Macbeth-Klm commented on scrapper/src/main/java/edu/java/scheduler/updater/jdbc/JdbcLinkUpdater.java
> +public interface JdbcLinkUpdater {
Проблема аналогична той, которую я описал выше. Я могу в данных компонентах вынести в абстрактный класс метод `getDescription `и часть кода, где я получаю `GitHubResponse`, но стоит ли оно того. Как будто бы это не та общая логика, которую хотелось бы вынести.

2024-04-09 10:22 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scheduler/service/LinkUpdaterService.java
> +public interface LinkUpdaterService {
Это можно решить, связав классы `Link` и `LinkDto` общим интерфейсом.

2024-04-09 10:24 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scheduler/updater/jdbc/JdbcLinkUpdater.java
> +public interface JdbcLinkUpdater {
В данном случае проблему можно также решить общим интерфейсом для `Link` и `LinkDto`.

2024-04-09 10:26 UTC, nexen505 commented on scrapper/src/main/java/edu/java/scheduler/updater/jdbc/JdbcLinkUpdater.java
> +public interface JdbcLinkUpdater {
И по соображению насчет абстрактного класса согласен: в качестве практики стоит попробовать сделать хороший рефакторинг.

2024-04-10 13:31 UTC, nexen505 approved these changes

2024-04-10 18:28 UTC, merged