hw2: hw2 has been done
Macbeth-Klm/Tinkoff-java-course-2024 pull request #2
Opened 2024-02-22 00:08 UTC by Macbeth-Klm

2024-02-29 13:27 UTC, nexen505 requested changes

2024-02-29 13:27 UTC, nexen505 commented on scrapper/src/main/java/edu/java/LinkUpdaterScheduler.java
> +    @Scheduled(fixedDelayString = "#{@applicationConfig.scheduler.interval}")
Косметика: можно упростить выражение, если воспользоваться знаком `$` для получения конфигурационного свойства приложения.

2024-02-29 13:27 UTC, nexen505 commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +        return new RegularGitHubClient();
Проблема: тут и далее при создании адрес передается неявно, хотя есть конструктор адресом.

Предложение: инжектить зависимость на свойство приложения в этой конфигурации, а не внутри класса бина, и воспользоваться механизмом по умолчанию в `@Value`.

2024-02-29 13:27 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/LinkUpdaterSchedulerTest.java
> +    public void shouldCorrectUpdate() {
Мысль: какой-то странный тест. Сами замокали проброс исключение на вызове, и проверяем этот же мок :)

2024-02-29 13:27 UTC, nexen505 commented on scrapper/src/main/java/edu/java/clients/GitHubClient/RegularGitHubClient.java
> +        webClient = WebClient.builder().baseUrl(defaultUrl).build();
Проблема: тут и в соседнем клиенте при таком создании клиента вручную теряются предконфигурированные фреймворком компоненты.

Предложение: добавить в конструктор зависимость на `WebClient.Builder webClientBuilder` и использовать ее для создания клиента.

2024-02-29 13:27 UTC, nexen505 commented on scrapper/src/main/java/edu/java/clients/GitHubClient/RegularGitHubClient.java
> +            .mapNotNull(this::parseJson)
Мысль: думаю, тут можно уйти от явного парсинга, если воспользоваться перегруженным методом `bodyToMono` с `ParameterizedTypeReference`.

2024-02-29 22:18 UTC, Macbeth-Klm commented on scrapper/src/test/java/edu/java/scrapper/LinkUpdaterSchedulerTest.java
> +    public void shouldCorrectUpdate() {
Да это я уже по приколу написал ))000

2024-03-05 12:29 UTC, nexen505 approved these changes

2024-03-05 12:57 UTC, merged