hw3: hw3 has been done
Macbeth-Klm/Tinkoff-java-course-2024 pull request #4
Opened 2024-03-07 15:44 UTC by Macbeth-Klm

2024-03-07 15:59 UTC, Macbeth-Klm commented
Здравствуйте! Сделал rebase ветки. Проанализировал, что можно привнести в код из предыдущих заданий, и ничего не пришло в голову за исключением двух моментов: возникла идея связать как-то `BotService.java` с командами из дз1, которые `implements Command`, или же связать клиенты из дз2 с API модуля `scrapper`. Однако я решил не делать этого, так как предположил, что это будет в последующих заданиях.

2024-03-10 08:36 UTC, nexen505 requested changes

2024-03-10 08:36 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/configuration/BotConfig.java
> +    WebClient.Builder webClientBuilder() {
Проблема: компонент дублирует аналогичный из "коробки" Spring Boot.

Предложение: уйти от него в пользу стандартного.

2024-03-10 08:36 UTC, nexen505 commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
>      WebClient.Builder webClientBuilder() {
Проблема: не заметил в прошлый раз, что компонент дублирует аналогичный из "коробки" Spring Boot.

Предложение: уйти в сторону использования стандартного компонента.

2024-03-10 08:36 UTC, nexen505 commented on scrapper/src/main/java/edu/java/dao/RegularUserDao.java
> +        users.put(id, new HashMap<>());
Проблема: `HashMap` не потокобезопасна, но используется в потокобезопасной среде.

Предложение: использовать потокобезопасный тип.

2024-03-14 13:54 UTC, nexen505 requested changes

2024-03-14 13:54 UTC, nexen505 commented on bot/src/main/java/edu/java/bot/configuration/BotConfig.java
> +    private final WebClient.Builder webClientBuilder = WebClient.builder();
Проблема: компонент по-прежнему дублирует аналогичный из "коробки" Spring Boot.

Предложение: уйти от него в пользу стандартного с использованием инъекции зависимостей.

2024-03-14 13:54 UTC, nexen505 commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> +    private final WebClient.Builder webClientBuilder = WebClient.builder();
Проблема: компонент дублирует аналогичный из "коробки" Spring Boot.

Предложение: уйти от него в пользу стандартного с использованием инъекции зависимостей.

2024-03-14 13:54 UTC, nexen505 commented on scrapper/src/main/java/edu/java/configuration/ClientConfiguration.java
> -    WebClient.Builder webClientBuilder() {
Подсказка: этот компонент объявлять необязательно, потому что Spring Boot уже его предсоздает.

2024-03-14 13:54 UTC, nexen505 commented on scrapper/src/main/java/edu/java/dao/RegularUserDao.java
> +public class RegularUserDao implements UserDao {
Мысль: реализация в целом непотокобезопасная в итоге, но тут за этим мы гнаться не будем, так как в будущем она станет не нужна.

2024-03-15 18:33 UTC, nexen505 approved these changes

2024-03-15 19:16 UTC, merged