hw4: hw4 has been done
Macbeth-Klm/Tinkoff-java-course-2024 pull request #5
Opened 2024-03-10 16:45 UTC by Macbeth-Klm

2024-03-15 13:25 UTC, Macbeth-Klm commented
Сори, что закинул пару коммитов 15-го марта, просто для выполнения дз5 требовалось изменить архитектуру бд.

2024-03-15 19:24 UTC, nexen505 requested changes

2024-03-15 19:24 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            Database database = DatabaseFactory.getInstance()
Проблема: ресурс не закрывается.

Предложение: добавить его в try-with-resources.

2024-03-15 19:24 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            Liquibase liquibase =
Проблема: ресурс не закрывается.

Предложение: добавить его в try-with-resources.

2024-03-15 19:24 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            liquibase.update(new Contexts(), new LabelExpression());
Предложение: добавить тест на запросы к БД. Проверить, что, например, создались нужные таблицы и т.п.

2024-03-19 11:39 UTC, nexen505 requested changes

2024-03-19 11:39 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            liquibase.update(new Contexts(), new LabelExpression());
Проблема: у меня локально миграции падают

```java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.RuntimeException: org.postgresql.util.PSQLException: Подсоединение по адресу localhost:32775 отклонено. Проверьте что хост и порт указаны правильно и что postmaster принимает TCP/IP-подсоединения.
	at edu.java.scrapper.IntegrationTest.runMigrations(IntegrationTest.java:47)
	at edu.java.scrapper.IntegrationTest.<clinit>(IntegrationTest.java:28)
	... 8 more
Caused by: org.postgresql.util.PSQLException: Подсоединение по адресу localhost:32775 отклонено. Проверьте что хост и порт указаны правильно и что postmaster принимает TCP/IP-подсоединения.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:342)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
	at org.postgresql.Driver.makeConnection(Driver.java:443)
	at org.postgresql.Driver.connect(Driver.java:297)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:683)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:230)
	at edu.java.scrapper.IntegrationTest.runMigrations(IntegrationTest.java:38)
	... 9 more
Caused by: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.pollConnect(Native Method)
	at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:682)
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:592)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:243)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:132)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
	... 16 more
```

Предложение: уточнить стратегию ожидания старта контейнера (см. `Wait#forListeningPort()`).

2024-03-19 12:23 UTC, Macbeth-Klm commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            liquibase.update(new Contexts(), new LabelExpression());
Я потратил на эту проблему весь день и так не смог решить. В итоге я поднимал бд для следующих заданий так: запустил сначала Postgresql контенейнер, потом с Luquibase контейнер. Несмотря на то, что в compose.yml liquibase-migrations содержит depends_on, он всё равно падает. Сейчас я добавил то, что вы предложили, но композник целиком все равно не запускается. Может, я не туда добавил. Надеюсь на вашу помощь.

2024-03-19 12:42 UTC, nexen505 approved these changes

2024-03-19 12:43 UTC, nexen505 commented on scrapper/src/test/java/edu/java/scrapper/IntegrationTest.java
> +            liquibase.update(new Contexts(), new LabelExpression());
А у меня с compose все локально хорошо. По текущему заданию все стало корректно тоже.

Если есть конкретная ошибка или проблема тут, можешь ко мне в ЛС в Telegram зайти и поизучаем.

2024-03-19 13:33 UTC, merged