hw5: hw5 has been done
Macbeth-Klm/Tinkoff-java-course-2024 pull request #6
Opened 2024-03-18 02:00 UTC by Macbeth-Klm

2024-03-18 06:08 UTC, Macbeth-Klm commented
Я не стал писать тесты на сервисы, так как они по сути построены на тех же запросах, что реализованы в domain, только порой миксуются

2024-03-26 13:00 UTC, nexen505 requested changes

2024-03-26 13:00 UTC, nexen505 commented on scrapper/src/main/java/edu/java/api/domain/repository/JoinTableRepository.java
> +public interface JoinTableRepository {
Проблема: название `JoinTable` чрезвычайно неудачное в силу общности.

Предложение: переименовать везде `JoinTable` в более смысловую сущность (например, `ChatLink`).

2024-03-26 13:00 UTC, nexen505 commented on scrapper/src/main/java/edu/java/api/domain/repository/jdbc/JdbcChatRepository.java
> +    private final String dataAccessMessage = "Server error";
Косметика: тут и в других подобных местах такие поля могут быть статическими в силу константности.

2024-03-26 13:00 UTC, nexen505 commented on scrapper/src/main/java/edu/java/api/domain/repository/jdbc/JdbcChatRepository.java
> +                "SELECT * FROM chat WHERE chat_id = ?",
Проблема: проверка существования делается через лишнее чтение в память.

Предложение: использовать `exists` на уровне БД.

2024-03-26 13:00 UTC, nexen505 commented on scrapper/src/main/java/edu/java/api/domain/repository/jdbc/JdbcChatRepository.java
> +            throw new BadRequestException(
Мысль: на мой взгляд, это исключение уровня контроллера, а не репозитория. В связи с этим, не вижу смысла использовать его здесь.

2024-03-26 13:00 UTC, nexen505 commented on scrapper/src/main/java/edu/java/api/domain/repository/LinkRepository.java
> +    boolean isExist(URI url);
Опечатка:

```suggestion
    boolean exists(URI url);
```

2024-03-26 13:00 UTC, nexen505 commented on scrapper/src/main/java/edu/java/api/domain/repository/jdbc/JdbcJoinTableRepository.java
> +                "SELECT link_id, url FROM ((SELECT * FROM link_chat_join_table WHERE chat_id = ?)"
Проблема: подзапрос выглядит лишним.

Предложение: уйти от подзапроса в сторону `join` с внешней фильтрацией по условию в запросе.

2024-03-26 13:00 UTC, nexen505 commented on scrapper/src/main/java/edu/java/api/domain/repository/jdbc/JdbcLinkRepository.java
> +                String noLinksMessage = "There's not links";
Косметика: можно в константы вынести.

2024-03-26 13:00 UTC, nexen505 commented on scrapper/src/main/java/edu/java/api/service/jdbc/JdbcLinkService.java
> +        Long linkId = (jdbcLinkRepository.isExist(url))
Проблема: это все можно сделать одним запросом к БД.

Предложение: воспользоваться запросом на вставку с обработкой конфликта.

2024-03-26 13:00 UTC, nexen505 commented on scrapper/src/main/java/edu/java/api/service/jdbc/JdbcLinkService.java
> +    public LinkResponse add(Long tgChatId, URI url) {
Проблема: тут и в других местах в рамках одного метода несколько запросов к БД выполняются в разных транзакциях.

Предложение: сделать методы сервиса целостно транзакционными.

2024-03-26 13:00 UTC, nexen505 commented on scrapper/src/main/java/edu/java/api/domain/repository/jdbc/JdbcChatRepository.java
> +    @Transactional
Проблема: тут и в других репозиториях открывается транзакция на запись, хотя происходит только чтение.

Предложение: использовать `readonly` в случае, если происходит только чтение.

2024-03-28 12:34 UTC, nexen505 approved these changes

2024-03-28 19:26 UTC, merged